---
services:
  proxy:
    build:
      context: .
    ports:
      - 443:443
      - 80:80
    environment:
      BACKEND: nginx:80
      DOMAIN: acme.com
    volumes:
      - ./persist:/data

  nginx:
    image: nginx:latest
